config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :pages

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post 

  def create
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to @post
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  private
    def comment_params
      params.require(:comment).permit(:name, :content)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end
  
  def show
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    @page.save
    redirect_to @page
  end

  def edit
  end

  def update
    @page.update(page_params)
    redirect_to @page
  end

  def destroy
    @page.destroy
    redirect_to pages_path
  end

  private
    def page_params
      params.require(:page).permit(:title, :body, :slug)
    end

    def set_page
      @page = Page.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div>
  <strong> <%= comment.name %> says: </strong>
  <%= comment.content %>
  <div class="comment-admin">
    <%= link_to "Edit", edit_post_comment_path(@post, comment) %>
    <%= link_to "Delete", [@post, comment], method: :delete %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@post, comment] do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name%>
  </div>

  <div class="field">
    <%= f.label :conent, "Comment" %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment:</h1>
<%= render partial: "form", locals: {comment: @comment} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
    <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Form to edit: <%= @page.title %></h1>

<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<h1>Blog</h1>

<% @pages.each do |page| %>
  <p><%= link_to page.title, page_path(page) %></p>
<% end %>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>

<p>
  <%= @page.body %>
</p>

<%= link_to "Edit", edit_page_path(@page) %>
<%= link_to "Delete", @page, method: :delete %>

app/views/partials/_header.html.erb
<div>
<h1><%= link_to 'Home', pages_path %></h1>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_header.html.erb
<div>
<h1><%= link_to 'Home', posts_path %></h1>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
                <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Title:</strong>
  <%= @post.title %>
</h1>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>


<div id="comments">
<% if @post.comments.present? %>
  <h1>Comments:</h1>
    <%= render @post.comments %>
<% end %>
    <h2>Add a Comment:</h2>
    <%= render partial: "comments/form", locals: {comment: @post.comments.new} %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>